version: '3'

services:
  # --- Snippet API ---
  snippet_api:
    container_name: "snippet-api"
    image: ghcr.io/ingsis-students/ingsis-snippet${ENVIRONMENT_FLAG}:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${SNIPPET_DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      spring.security.oauth2.resourceserver.jwt.issuer-uri: ${AUTH_SERVER_URI}
    ports:
      - '8082:8080'
    depends_on:
      - snippet-db

  snippet-db:
    container_name: "snippet-db"
    image: postgres:12
    ports:
      - '5002:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${SNIPPET_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SNIPPET_POSTGRES_DB}
    volumes:
      - db-data-ingsis-snippet:/var/lib/postgresql/data

  # --- Permissions API ---
  permissions_api:
    container_name: "permissions-api"
    image: ghcr.io/ingsis-students/ingsis-permission${ENVIRONMENT_FLAG}:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PERMISSIONS_DB_HOST}:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      spring.security.oauth2.resourceserver.jwt.issuer-uri: ${AUTH_SERVER_URI}
    ports:
      - '8083:8080'
    depends_on:
      - permission-db

  permission-db:
    container_name: "permission-db"
    image: postgres:12
    ports:
      - '5003:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data-ingsis-user:/var/lib/postgresql/data

  # --- Parse API ---
  printscript_api:
    container_name: "printscript-api"
    image: ghcr.io/ingsis-students/ingsis-parse${ENVIRONMENT_FLAG}:latest
    ports:
      - '8081:8080'
    environment:
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH_SERVER_URI: ${AUTH_SERVER_URI}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}

volumes:
  db-data-ingsis-snippet:
    external: false
  db-data-ingsis-user:
    external: false