version: '3'

services:
  # Spring app service for Snippet API
  snippet_api:
    container_name: "snippet-api"
    image: ghcr.io/ignaciochevallier/ingsis-snippet:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ingsis-snippet-db:5002/postgres
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '8082:8080'
    depends_on:
      - ingsis-snippet-db

  # Postgres Database for Snippet API
  ingsis-snippet-db:
    image: postgres:12
    ports:
      - '5002:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data-ingsis-snippet:/var/lib/postgresql/data




  # Spring app service for User API
  spring_api:
    container_name: "user-api"
    image: ghcr.io/matichialvaa/ingsis-permission:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ingsis-permission-db:5003/postgres
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '8083:8080'
    depends_on:
      - ingsis-permission-db

  #Postgres Database
  ingsis-permission-db:
    image: postgres:12 #si le ponemos alpine, hay q cambiar de permission tamb.
    ports:
      - '5003:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data-ingsis-user:/var/lib/postgresql/data



  # PrintScript API
  printscript_api:
    container_name: "printscript-api"
    image: ghcr.io/tomasvalleduran/ingsis-parse:latest
    ports:
      - '8081:8080'



# Volúmenes persistentes para las bases de datos
volumes:
  db-data-ingsis-snippet:
    external: false
  db-data-ingsis-user:
    external: false
