name: deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Load environment variables from .env
        run: |
          export $(cat /.env | xargs)

      - name: Pull latest code from GitHub
        run: |
          ssh -o StrictHostKeyChecking=no students@20.70.208.179 'cd ~/ingsis-infra && GITHUB_USER=your_username GITHUB_TOKEN=your_token git pull https://$GITHUB_USER:$GITHUB_TOKEN@github.com/your_username/your_repo.git'