name: Master Workflow
run-name: Continuous Integration

on:
  push:
    branches:
      - main
      - prod

jobs:
  pull-to-virtual-machine:
    name: pull changes to vm
    uses: ./.github/workflows/pull-to-vm.yml
    with:
      host: ${{ github.ref_name == 'main' && '20.70.208.179' || '20.213.8.120' }}
      user: ${{ github.ref_name == 'main' && 'students' || 'matichialva' }}
      gh_user: 'TomasValleDuran'
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      pat: ${{ secrets.PAT }}