name: update docker images in virtual machine

on:
  workflow_call:
    inputs:
      host:
        description: 'Virtual Machine Host IP'
        required: true
        type: string
      user:
        description: 'Virtual Machine User'
        required: true
        type: string
      gh_user:
        description: 'GitHub User'
        required: true
        type: string
    secrets:
      key:
        description: 'SSH Private Key to access the virtual machine'
        required: true
      pat:
        description: 'GitHub Personal Access Token'
        required: true


jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute remote git pull via SSH
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.user }}
        key: ${{ secrets.key }}
        script: |
          cd ingsis-infra
          git pull origin main
          sudo docker compose down